services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: EduNotes_db
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - EduNotes_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/EduNotes_db
    depends_on:
      - db

volumes:
  EduNotes_data: