"""cascadeTOPIC

Revision ID: 1954c4acdcf2
Revises: 1cbf9541b29c
Create Date: 2025-07-24 12:38:09.135186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1954c4acdcf2'
down_revision: Union[str, Sequence[str], None] = '1cbf9541b29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('topics_organization_id_fkey'), 'topics', type_='foreignkey')
    op.create_foreign_key(None, 'topics', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.create_foreign_key(op.f('topics_organization_id_fkey'), 'topics', 'organizations', ['organization_id'], ['organization_id'])
    # ### end Alembic commands ###
