"""Note_like table added

Revision ID: 35a8c693b7bc
Revises: 2be86b9706b4
Create Date: 2025-07-24 00:48:50.125667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a8c693b7bc'
down_revision: Union[str, Sequence[str], None] = '2be86b9706b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('like', 'dislike', name='liketypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.note_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'user_id', name='unique_note_user_like')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_likes')
    # ### end Alembic commands ###
