"""deadlines added

Revision ID: 674a863b651b
Revises: e81cf9065bda
Create Date: 2025-07-28 17:33:39.711921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674a863b651b'
down_revision: Union[str, Sequence[str], None] = 'e81cf9065bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deadlines',
    sa.Column('deadline_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('exam', 'assignment', name='eventtypeenum'), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_description', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deadline_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deadlines')
    # ### end Alembic commands ###
