"""note-notelike relationshpi added

Revision ID: 9dfe74a9f9f3
Revises: dd5305385b4c
Create Date: 2025-07-29 14:06:39.786421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfe74a9f9f3'
down_revision: Union[str, Sequence[str], None] = 'dd5305385b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
