"""invitations model| ivtitations added to users and organizations

Revision ID: d1ff26b6e014
Revises: 4fafdc769994
Create Date: 2025-07-21 22:29:42.084923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1ff26b6e014'
down_revision: Union[str, Sequence[str], None] = '4fafdc769994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.Enum('user', 'owner', name='inviteduserroleenum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='statusenum'), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.organization_id'], ),
    sa.PrimaryKeyConstraint('invitation_id')
    )
    op.create_index(op.f('ix_organization_invitations_invitation_id'), 'organization_invitations', ['invitation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_invitations_invitation_id'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    # ### end Alembic commands ###
