"""CASCADE for orgazniations

Revision ID: d5e958148ff4
Revises: 1913298e9909
Create Date: 2025-07-24 12:29:57.045034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e958148ff4'
down_revision: Union[str, Sequence[str], None] = '1913298e9909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('channels_organization_id_fkey'), 'channels', type_='foreignkey')
    op.create_foreign_key(None, 'channels', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notes_organization_id_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('organization_invitations_organization_id_fkey'), 'organization_invitations', type_='foreignkey')
    op.create_foreign_key(None, 'organization_invitations', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('organization_users_organization_id_fkey'), 'organization_users', type_='foreignkey')
    op.create_foreign_key(None, 'organization_users', 'organizations', ['organization_id'], ['organization_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_users', type_='foreignkey')
    op.create_foreign_key(op.f('organization_users_organization_id_fkey'), 'organization_users', 'organizations', ['organization_id'], ['organization_id'])
    op.drop_constraint(None, 'organization_invitations', type_='foreignkey')
    op.create_foreign_key(op.f('organization_invitations_organization_id_fkey'), 'organization_invitations', 'organizations', ['organization_id'], ['organization_id'])
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_organization_id_fkey'), 'notes', 'organizations', ['organization_id'], ['organization_id'])
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.create_foreign_key(op.f('channels_organization_id_fkey'), 'channels', 'organizations', ['organization_id'], ['organization_id'])
    # ### end Alembic commands ###
